sudo : required
language: node_js
node_js:
  - 7
services :
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t ujjwal25/complex-client ./client 


script:
  - docker run -e CI=true ujjwal25/complex-client npm run test 

after_success:
  - docker build  -t ujjwal25/multi-client ./client 
  - docker build  -t ujjwal25/multi-nginx ./nginx 
  - docker build  -t ujjwal25/multi-server ./server 
  - docker build  -t ujjwal25/multi-worker ./worker 
  #Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push all images to docker hub
  - docker push ujjwal25/multi-client
  - docker push ujjwal25/multi-nginx 
  - docker push ujjwal25/multi-server
  - docker push ujjwal25/multi-worker


# deploy:
#   provider: elasticbeanstack
#   region: "us-east-1"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "not enered"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_acces_key: $AWS_SECRET_KEY
#   skip_cleanup: true